### ISSUE TITLE
Peer management api ability to delete/update

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#115]

**Comment by mdobson** [comment]
I've got this one.

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>

**Comment by mdobson** [comment]
For clarity sake. 

- Deleting a peer will disconnect from the server.
- Updating a peer will connect to new server, and then disconnect from old server. 

How does that sound?
