### ISSUE TITLE
Large peer registry kept zetta http server from running

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#123]
Not sure what causing the registry to fill up or create so many data files.

**Comment by mdobson** [comment]
Two pronged. 

1. Investigate compaction

2. Investigate why Zetta can't start it's server with giant files.

**Comment by mdobson** [comment]
@AdamMagaluk and @kevinswiber should we port the peer registry stuff to use calypso as well? I remember we talked about it a while ago. This may be the time to strike.

**Comment by AdamMagaluk** [comment]
If it's straight forward I don't see why not. Like we talked earlier it would be great if both the peer_registry and the registry were built from the same base which could include the calypso hooks and compaction logic.

**Comment by mdobson** [comment]
See #124
