### ISSUE TITLE
Linking API outside of initial server startup

### ISSUE THREAD

**Issue by mdobson** [zettajs/zetta#126]
Here is an interesting issue. The following code won't do what we think it would do. It will just sit there doing nothing. Should we investigate doing a patch on this part of the API to handle this scenario?

```javascript
var zetta = require('zetta');

var inst = zetta()
  .name('mdobs')
  .listen(1337, function(err) {
    if(!err) {
      inst.link('http://hello-zetta.herokuapp.com/');
    }
  });
```

This work around will remedy the issue, but doesn't account for the peer cleanup process which is another internal function.

```javascript
var inst = zetta()
  .name('mdobs')
  .listen(1337, function(err) {
      inst.link('http://hello-zetta.herokuapp.com/');
      inst._initPeers(function(err) {
        if(err) {
          console.log(err);  
         } 
       });  
  });
```

**Comment by kevinswiber** [comment]
Yeah, this is a good one.  Should be an easy fix.  We can change functionality in `.link` so it acts differently depending on whether or not the peers have already been through initialization.
