### ISSUE TITLE
Not handling spdy agent error event

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#137]
In `lib/peer_socket` we're setting a spdy agent but not handling the error event on it. See: https://github.com/zettajs/zetta/blob/master/lib/peer_socket.js#L121-L133

I saw this repeatably throw when continually connecting and disconnecting a peer.

Example to make the cloud throw a `ECONNRESET` or other error.

```js
var zetta = require('zetta');

var z = zetta()
  .link('http://localhost:5000')
  .listen(5002, function() {
    setInterval(function(){ 
      z._peerClients.forEach(function(p) {
        p._ws.close();
      })
    }, 1000)
  });
```
We can handle the error like: PR coming soon.

```js
this.agent.on('error', function(err) {
  self.close();
  self.emit('error', err);
})
```

**Comment by AdamMagaluk** [comment]
Cloud looks like:

```js
var zetta = require('zetta');

zetta()
  .listen(5000);
```

**Comment by mdobson** [comment]
Reproduced.

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>
