### ISSUE TITLE
Can we remove unused modules from zetta.js file ?

### ISSUE THREAD

**Issue by anil614sagar** [zettajs/zetta#145]
Just noticed below modules are unused in zetta.js file. Can we remove them ?

var uuid = require('node-uuid');
var Device = require('zetta-device');
var HttpDevice = require('zetta-http-device');
var Scout = require('zetta-scout');

**Comment by mdobson** [comment]
Good catch @anil614sagar can you submit a PR for this?

**Comment by anil614sagar** [comment]
Thank you @mdobson . Created pull request for same https://github.com/zettajs/zetta/pull/150
