### ISSUE TITLE
What is the reason behind zetta-http-device module in zetta ?

### ISSUE THREAD

**Issue by anil614sagar** [zettajs/zetta#151]
I see it's being used only in example_http_driver.js file for testing. zetta-http-device module just inherits device class and doesn't add any new methods or properties.

Can we remove this module from zetta dependencies if not being used ? or am i missing some thing ?

**Comment by mdobson** [comment]
http devices are devices that potentially have a full access to network resources and can register themselves with zetta via the API.  This feature has been in flux since it's inception, and will be revisited soon. For now it's not hurting anything to keep it where it is.

-Matt
