### ISSUE TITLE
Properties on server object

### ISSUE THREAD

**Issue by mdobson** [zettajs/zetta#154]
We can set the servers `"name"` property, but no others. Would this be something that should be extended to multiple kinds of properties?

**Comment by anil614sagar** [comment]
+ 1

@mdobson : can we have an array called _properties and use that to store key, value objects of properties.

Something like code below ?

Zetta.prototype.setProperty = function(propertyName, propertyValue) {
  var property = {};
  property[propertyName] = propertyValue;
  this._properties.push(property);
  return this;
};

**Comment by kevinswiber** [comment]
@anil614sagar 

Thinking more along the lines of:

```js
zetta()
  .properties({
    location: 'theater-7',
    owner: 'AMC'
  })
  .listen(1337);
```

The server API response would contain both `location` and `owner` in the representation.  (This would be true for both the entities representation at the root and the individual representations at `/servers/{id}`.

Thoughts?  @AdamMagaluk @mdobson

**Comment by anil614sagar** [comment]
+1
