### ISSUE TITLE
Use cycle.js to avoid circular references in the device api response

### ISSUE THREAD

**Issue by rkyleg** [zettajs/zetta#166]
I wrote a driver for arduino boards using the johnny-five library. In the api response the key 'board' is referenced in several places in the device 'entities' section of the api response. The register key holds an entry for board as does the repl key (from johnny-five). Also, because I assigned an led to each LED device, the led key holds a reference to board. This causes the error: TypeError: Converting circular structure to JSON because of the JSON.stringify operation in the argo library (argo.js line 230). I used the cycle.js package in the JSON.stringify call to make sure that keys that have been seen before aren't evaluated infinitely. 

This is how I added cycle.js to argo.js:

```javascript
var util = require('util');
var cycle = require('cycle');
console.log(util.inspect(body, {depth: 5}));
body = new Buffer(JSON.stringify(cycle.decycle(body)), 'utf-8');
```

This avoids the error when running the JSON.stringify operation on the api response; instead of recursing through the board key over and over, it simply prints [Circular] after the first instance of the 'board' key. This hasn't interfered with any of the other keys so far. 

Here is the api output I got: 

[Pastebin](http://pastebin.com/hWWtSbX2)

[Cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js)

Also link to the driver:
 [zetta-led-arduino-driver](https://github.com/rkyleg/zetta-led-arduino-driver)

I'm a bit of a novice so let me know if I didn't explain anything clearly enough

**Comment by kevinswiber** [comment]
Hey @rkyleg, thanks for diving into that issue.  Feel free to file a pull request on [argo/argo](/argo/argo).

When using Zetta, we usually consider something like the LED driver's "arduino" property to be a private property.  Private properties do not show up in the API response.  We do this by convention.  You can designate a property as private by prefixing it with an underscore.  So if you were using `led._arduino`, for example, the board object internals would not be exposed through the API.  Just an alternative to consider.  :)

**Comment by rkyleg** [comment]
Hey Kevin, thanks for the response, I was re-writing my driver last night after looking at this example:
https://github.com/switzersc/watchdog. I did change my led object references to be private properties and the issue seems to be resolved. I learned something about Javascript properties in the process. 

Do you specifically ignore private properties in the argo package, or is that something done automatically by JSON.stringify because private properties are not enumerable?

**Comment by kevinswiber** [comment]
It's a convention we enforce in Zetta before the HTTP response gets sent
through Argo.

See here:
https://github.com/zettajs/zetta-device/blob/master/device.js#L154-L158

On Mon, Mar 23, 2015 at 3:26 PM, rkyleg <notifications@github.com> wrote:

> Hey Kevin, thanks for the response, I was re-writing my driver last night
> after looking at this example:
> https://github.com/switzersc/watchdog. I did change my led object
> references to be private properties and the issue seems to be resolved. I
> learned something about Javascript properties in the process.
>
> Do you specifically ignore private properties in the argo package, or is
> that something done automatically by JSON.stringify because private
> properties are not enumerable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zettajs/zetta/issues/166#issuecomment-85158128>.
>



-- 
Kevin Swiber
Projects: https://github.com/kevinswiber
Twitter: @kevinswiber

**Comment by rkyleg** [comment]
That's really helpful! Thank you, and thanks for ZettaJS!

**Comment by mdobson** [comment]
Closing this for now.
