### ISSUE TITLE
Allow SPDY as a protocol for client-to-server connections.

### ISSUE THREAD

**Issue by kevinswiber** [zettajs/zetta#192]
Let's take pieces of Zetta's server-to-server protocol and expose that in a client-to-server interface.

Specifically, let's reuse

* [State Requests](https://gist.github.com/kevinswiber/e8b0577ad01dea8a9394#3-state-requests)
* [Transition Requests](https://gist.github.com/kevinswiber/e8b0577ad01dea8a9394#4-transition-requests)
* [Stream Requests](https://gist.github.com/kevinswiber/e8b0577ad01dea8a9394#5-stream-requests)
* [Ping Requests](https://gist.github.com/kevinswiber/e8b0577ad01dea8a9394#6-ping-requests)

This will allow clients to connect to Zetta using a single TCP connection.

**Comment by mdobson** [comment]
Implemented in zetta@0.30.0
