### ISSUE TITLE
Query support for *

### ISSUE THREAD

**Issue by mdobson** [zettajs/zetta#196]
We have support for multi server queries in the API, but not in JS.

This should work for parity with our HTTP API.

```javascript
module.exports = function(server) {
  var q = server.from('*').where('type = "photocell"');
  server.observe([q], function(device) {
    console.log(device);
  });
}
```

**Comment by kevinswiber** [comment]
Hint: https://github.com/zettajs/zetta/blob/master/lib/runtime.js#L122

**Comment by AdamMagaluk** [comment]
See: #199
