### ISSUE TITLE
Scout for unknown number of devices

### ISSUE THREAD

**Issue by tomikpik** [zettajs/zetta#212]
Hi, I would like to ask if it is possible to make scout that will be looking for unknown number devices of given type continuously. If yes, then how? 
Thanks a lot
Tom

**Comment by mdobson** [comment]
Hey @tomikpik 

Yes it is possible for scouts to look for a number of devices of a given type continuously. A good example is in our Sonos scout. The library the scout uses for finding Sonos devices will just emit events as they come online, and we pass those device objects over to Zetta.

Any device in particular you're looking to scout for? That could help me nail down a more particular case.

-Matt

```javascript
var sonos = require('sonos');
var Scout = require('zetta-scout');
var util = require('util');
var SonosDriver = require('./sonos_driver');

var SonosScout = module.exports = function() {
  Scout.call(this);
};
util.inherits(SonosScout, Scout);

SonosScout.prototype.init = function(next) {
  var self = this;
  sonos.search(function(device) {
    self.discover(SonosDriver, device);
  });
  next();
};
```

**Comment by tomikpik** [comment]
Thanks a lot. 
I understand how scouting works, however I don't know how to connect unknown sensors during runtime. I can see, that we can use scout, but I'm not sure how.
Let's imagine you have a LED and you have driver for it. At some random point you connect the LED, will the scout discover it?

**Comment by mdobson** [comment]
Yes. The LED will be discovered and wired into the system automatically.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]
