### ISSUE TITLE
Multiple devices from single data stream

### ISSUE THREAD

**Issue by tomikpik** [zettajs/zetta#213]
We are making IOT project in which our sensor is "concentrator" of all the sensors. What I mean by this is that from our sensor (concentrator) we get all the data from multiple different sensors. Is there any way to observe the stream of data and dynamically recognize different devices and connect them using separate drivers?

**Comment by mdobson** [comment]
Hi @tomikpik 

I need a little clarification. Do you have all sensor streams coming into a single Zetta device you'd like to separate into multiple? Or do you have multiple Zetta devices that will send their sensor streams to a concentrator Zetta device?

**Comment by tomikpik** [comment]
All sensor streams is coming into single Zetta device and I would like to separate it into multiple devices.

**Comment by AdamMagaluk** [comment]
Hi @tomikpik 

Could you separate the sensor streams in the scout and pass them along to the appropriate zetta device?
