### ISSUE TITLE
Slow WebSocket Disconnects

### ISSUE THREAD

**Issue by wooliet** [zettajs/zetta#217]
I am able to successfully open a websocket connection in Chrome to a monitor a device property. The connection seems to happen immediately, and messages arrive as soon as they occur. 

However, when I close the socket, it takes right at one minute before the `onclose` event handler is triggered. It seems like the close command is not actually handled by the server, and the connection just times out.

**Comment by mdobson** [comment]
Hey William

Can you shoot me an email with a web socket link that shows off this behavior?

-Matt

**Comment by AdamMagaluk** [comment]
Non-issue on plain Zetta, see response in email.
