### ISSUE TITLE
WebSocket event communication

### ISSUE THREAD

**Issue by novotmike** [zettajs/zetta#220]
Hello, 
this past month I have been playing with Zetta and I'd like to know if there is a way to send evens (or any other custom message/command) through WebSocket, which exists between two (or more) Zettas (p2p).
I understand that data is exchanged, but I'm not sure, how to send some custom data on which I can react on the other peer (some handler).

- I also noticed that there is (possibly) similar issue already - are you planning the handlers for websocket in other version of Zetta or is it there already?

**Comment by mdobson** [comment]
Hi @novotmike!

I'm not 100% following your question. Current Zetta API websockets are read only streams. Here is the primary use cases.

Case 1:

```
//Z1 = Zetta Hub
//We open a websocket to Z1 to read a sensor stream
client -- ws:// request --> Z1
//We send those sensor stream readings back
client <-- Data ------------- Z1
```

Case 2:
```
//Z1 = Zetta Hub
//Z2 = Zetta Clout
//We open a websocket to Z2 to read a sensor stream it proxies this down to Z1 where the sensor is.
client -- ws:// request --> Z2 ------------> Z1
//We send those sensor stream readings back
client <- Data ------ Z2 <------------ Z1
```
Currently those are the cases which we can send data back and forth between peers. We don't have anything for doing custom message passing.

**Comment by novotmike** [comment]
Ok thank you for this explanation. I understand both cases.
 For my case I need to send messages that aren't necessarily API requests. 
I will probably have to implement my own comunication - what would be the best way to do it given the current architecture?

**Comment by mdobson** [comment]
Could you delve into your use case? You'd like to use websockets to
communicate between Zetta instances?

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by novotmike** [comment]
Of course.
My case consists of one controlling cloud service on which I have my own server connected with zetta server instance.
"At home" I have multiple Zetta instances, which are linked to the "cloud" Zetta.
For my case I have to be able to send messages from "cloud" Zetta to the linked instances so that I can manipulate my sensors and give instructions.
And as you said I would like  to be able to communicate between all instances of Zetta via websocket.
I'm not really sure what is the best way to do it. I guess I can simply create my own communication channel, but is that really the right way to do it?

**Comment by mdobson** [comment]
Let me know if I'm still misunderstanding you, but we do have something that can help you accomplish that.

Zetta has a concept of internal *apps* little stateless pieces of javascript that can live in your Zetta server. They can query for devices, and orchestrate some interesting interactions between devices that include message passing functionality.

Here is a quick example. 

```
//You have three Zetta servers
// Zc = Zetta cloud
// Z1, Z2 = Zetta hubs
// Z1 and Z2 are linked to Zc. Z1 has an LED attached to it, and Z2 has a button attached to it.
// With a remote query we can have an LED turn on or off based on the push state of the button on Z2.
       Zc <-- The coordinating app would live here
      /     \
    Z1   Z2
   /          \
LED      Button
```

Here is what the JS would look like.

```javascript
//app.js
module.exports = function(server) {
  var buttonQuery = server.from('Z2').where('type = "button"');
  var ledQuery = server.from('Z1').where('type = "LED"');
  server.observe([buttonQuery, ledQuery], function(button, led) {
    button.on('pressed', function() {
      led.call('turn-on');
    });
  });
}
```
Here is how you would use that in a Zetta server.

```javascript
//Zc - Zetta cloud file.
var zetta = require('zetta');
var app = require('./app');

zetta()
  .name('Zc')
  .use(app)
  .listen(1337);
```

**Comment by novotmike** [comment]
You are not misunderstanding me. What you showed me here is helpful. Thank you very much.
But I can still see, that the "communication" is between 2 Devices (drivers) am I right?
What if I want to controll the Z1 and Z2 from Zc - for example tell something to a scout or other component. Is that possible with Zetta App?

**Comment by mdobson** [comment]
Not exactly, but we do have a few extension points in different parts of Zetta that could hopefully support that scenario. I'll try and cook something up that may help you.

**Comment by mdobson** [comment]
So after thinking about it. You can embed a zetta device into a scout. Something like this should be possible. Though you may want a generic device that can receive transitions and whatnot.

```javascript
var sonos = require('sonos');
var Scout = require('zetta-scout');
var util = require('util');
var ButtonDriver = require('./button_driver');
var ButtonScout = module.exports = function() {
  Scout.call(this);
};
util.inherits(ButtonScout, Scout);

ButtonScout.prototype.init = function(next) {
  var self = this;
  //this.server is a property on the superclass
  var q = self.server.from('Z1').where({type: 'led'});
  self.server.observe([q], function(led) {
    led.on('turn-on', function() {
      self.discover(ButtonDriver);
    });
  });
  next();
};
```

**Comment by novotmike** [comment]
That looks very interesting. I'll give it a try and tell you if it works the way I need.
Thank you.

**Comment by AdamMagaluk** [comment]
Closing issue, can reopen if needed.
