### ISSUE TITLE
Websocket endpoint for /peer-management/<hub_id> does not work.

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#233]
On api responses for `GET /peer-management` and `GET /peer-management/<hub_id>` we provide a monitor link to both `WS /peer-management` and `WS /peer-management/<hub_id>` the first works and we get connect and disconnect events for all peers to and from that server but the latter does not work. Just disconnects right away.

**Comment by kevinswiber** [comment]
Perhaps we should just remove it?  I'm not sure what it's supposed to do.
