### ISSUE TITLE
Mutliplexed WebSocket - Receiving events from non-subscription sources

### ISSUE THREAD

**Issue by kyork-cl** [zettajs/zetta#252]
Both of the following subscriptions resulted in events from devices that did not match the "topic"

        {"type": "subscribe","topic": "*/light/**"}
        {"type": "subscribe","topic": "*/light/*/*"}

I received events from `"topic":"b811648e-9dde-40c1-a3a8-53e52e3e6f1f/service/e0c042f2-523e-4657-af1c-e25caf3ceaf7/stdout"`.

**Comment by kyork-cl** [comment]
Event when I specify a full topic, `{"type": "subscribe","topic": "b811648e-9dde-40c1-a3a8-53e52e3e6f1f/light/7b8d4b4e-5f83-47a9-86a1-8b885104d078/onOff"}` I still receive events from other sources.

**Comment by mdobson** [comment]
Have you sent multiple subscriptions down the websocket? When you get a
subscribe-ack it also gives you a subscriptionId that will allow you to
correlate messages to the particular subscription you created.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by kyork-cl** [comment]
No, these are all coming down a single subscription.

        wscat -c ws://zetta-v1-beta.herokuapp.com/events
        connected (press CTRL+C to quit)
        > {"type": "subscribe","topic": "jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature"}
          < {"type":"subscribe-ack","timestamp":1446130421043,"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","subscriptionId":1}
          < {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/2ccb7230-d83c-4ffe-b4e7-b02aa636aa43/currentTemperature","timestamp":1446130421056,"data":25.44,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/2ccb7230-d83c-4ffe-b4e7-b02aa636aa43/currentTemperature","timestamp":1446130421056,"data":25.44,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446130422079,"data":24.48,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446130422079,"data":24.48,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446130422704,"data":24.36,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446130422704,"data":24.36,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446130422741,"data":24.18,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446130422741,"data":24.18,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446130423955,"data":25.21,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446130423955,"data":25.21,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446130424575,"data":24.64,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446130424575,"data":24.64,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446130424915,"data":25.3,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446130424915,"data":25.3,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446130424915,"data":25.3,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/0643e9c0-f853-4efc-8716-1799bd5cfea8/currentTemperature","timestamp":1446130425160,"data":24.36,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/0643e9c0-f853-4efc-8716-1799bd5cfea8/currentTemperature","timestamp":1446130425160,"data":24.36,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/currentTemperature","timestamp":1446130425247,"data":23.51,"type":"event","subscriptionId":1}
          < {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/currentTemperature","timestamp":1446130425247,"data":23.51,"type":"event","subscriptionId":1}
        > %

**Comment by mdobson** [comment]
Can you give us the wscat result from the initial issue you filed?

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by kyork-cl** [comment]
Single Wildcard
        
        [2K[E[32mconnected (press CTRL+C to quit)[39m
        > > [2K[E[34m< {"type":"subscribe-ack","timestamp":1446131111030,"topic":"*/light/*/*","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/0643e9c0-f853-4efc-8716-1799bd5cfea8/currentTemperature","timestamp":1446131110989,"data":25.1,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/currentTemperature","timestamp":1446131111073,"data":25.8,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/6a23c66c-1ca7-4e25-b65e-827faa7cd568/currentTemperature","timestamp":1446131111252,"data":23.97,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/2ccb7230-d83c-4ffe-b4e7-b02aa636aa43/currentTemperature","timestamp":1446131111799,"data":24.68,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446131112857,"data":24.4,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446131113510,"data":25.74,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446131113526,"data":25.28,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446131114742,"data":25.39,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446131115351,"data":25.33,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446131115687,"data":25.96,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/0643e9c0-f853-4efc-8716-1799bd5cfea8/currentTemperature","timestamp":1446131115993,"data":24.85,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/currentTemperature","timestamp":1446131116081,"data":26.03,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/relayState","timestamp":1446131116082,"data":"Cool,Fan","type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/6a23c66c-1ca7-4e25-b65e-827faa7cd568/currentTemperature","timestamp":1446131116257,"data":24.23,"type":"event","subscriptionId":1}[39m
        > 

Double Wildcard

        [2K[E[32mconnected (press CTRL+C to quit)[39m
        > > [2K[E[34m< {"type":"subscribe-ack","timestamp":1446131097665,"topic":"*/light/**","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446131097843,"data":25.18,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446131098484,"data":25.93,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446131098503,"data":26.13,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/relayState","timestamp":1446131098505,"data":"Cool,Fan","type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446131099718,"data":26.2,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-07b04501-1dad-47dc-b1b4-e1c4c0d9d83d/thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/relayState","timestamp":1446131099720,"data":"Cool,Fan","type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446131100338,"data":26.09,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/547607bb-f235-40eb-8283-c5db40fa572a/relayState","timestamp":1446131100339,"data":"Cool,Fan","type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446131100671,"data":25.64,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-31986ace-e485-469c-9e80-c3ec15d2a6f6/thermostat/0643e9c0-f853-4efc-8716-1799bd5cfea8/currentTemperature","timestamp":1446131100980,"data":25.6,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-f68374c6-158c-4b87-8d8f-e0335a4ba2ed/thermostat/9cd8d806-7dc2-4ac2-b58f-c2c3b314a030/currentTemperature","timestamp":1446131101062,"data":25.34,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/6a23c66c-1ca7-4e25-b65e-827faa7cd568/currentTemperature","timestamp":1446131101244,"data":24,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/thermostat/2ccb7230-d83c-4ffe-b4e7-b02aa636aa43/currentTemperature","timestamp":1446131101794,"data":24.25,"type":"event","subscriptionId":1}[39m
        > [2K[E[34m< {"topic":"jilia-sandbox-86751775-a896-48f8-b38d-2d04e7ee5955/thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446131102848,"data":24.89,"type":"event","subscriptionId":1}[39m
        >

**Comment by kyork-cl** [comment]
I have 6 servers connected to the http://zetta-v1-beta.herokuapp.com/ peer if you wanted to reproduce this for yourself.

**Comment by kyork-cl** [comment]
Also, if I subscribe to a specific websocket event stream, I get data from *ALL* sources as well

        wscat -c ws://zetta-v1-beta.herokuapp.com/servers/jilia-sandbox-8f1b56e6-0dc5-4e27-a031-f72808e49a11/events?topic=thermostat%2F2ccb7230-d83c-4ffe-b4e7-b02aa636aa43%2FcurrentTemperature
        connected (press CTRL+C to quit)
          < {"topic":"thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446131923558,"data":24.69}
          < {"topic":"thermostat/653ce306-311c-4fa8-ab42-5a618a632b08/currentTemperature","timestamp":1446131923558,"data":24.69}
          < {"topic":"thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446131924157,"data":25.77}
          < {"topic":"thermostat/8a79eb17-c28b-4a76-a1b7-b55e5ffb9036/currentTemperature","timestamp":1446131924157,"data":25.77}
          < {"topic":"thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446131924189,"data":25.89}
          < {"topic":"thermostat/975462eb-cdc6-4b77-8c09-bc54d134b060/currentTemperature","timestamp":1446131924189,"data":25.89}
          < {"topic":"thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446131925420,"data":25.66}
          < {"topic":"thermostat/65b5bd8d-42b1-4b30-a53a-80676b271fc5/currentTemperature","timestamp":1446131925420,"data":25.66}
          < {"topic":"thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446131925964,"data":25.6}
          < {"topic":"thermostat/547607bb-f235-40eb-8283-c5db40fa572a/currentTemperature","timestamp":1446131925964,"data":25.6}
          < {"topic":"thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446131926369,"data":25.98}
          < {"topic":"thermostat/128d0852-4731-4492-b375-73fc37124db5/currentTemperature","timestamp":1446131926369,"data":25.98}
        > %

**Comment by AdamMagaluk** [comment]
I'm gonna close this issue with the v1.0.0-beta.4 released. If any of these issues pop up please feel free to reopen.
