### ISSUE TITLE
Mutliplexed WebSocket - Duplicate messages for topics

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#254]
Cloud Zetta peered to two peers P1 and P2 both with one mock LED.

Subscribing to '*/led/*/state' when state changes on P1's led I get one message but when state changes on P2 it gets two events.

If I subscribe individually to the the led on either P1 or P2 I get double messages when state changes.

**Comment by mdobson** [comment]
Is this before or after the latest PR?

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by AdamMagaluk** [comment]
After
