### ISSUE TITLE
Extended chars in the status field of devices not handled properly 

### ISSUE THREAD

**Issue by earth2marsh** [zettajs/zetta#272]
Trying to post `ℂ◉℗⒴ ℘ⓐṨͲℰ Ⓒℌ◭ℝ◬ℂ⒯℮ℛ ` to a display replaced it with `????????…`

Maybe the Zetta API doesn't seem to support extended characters in the status field of devices?

<img width="201" alt="zetta_demo___nest" src="https://cloud.githubusercontent.com/assets/54582/11755289/23fbdd34-a006-11e5-8d8a-cb2fe8e3113d.png">

**Comment by AdamMagaluk** [comment]
This fix only fixes the zetta api response issue. The screen is a different issue in firmware that probably won't get fixed any time soon.
