### ISSUE TITLE
Root resource returning 200 for QL request if no server provided

### ISSUE THREAD

**Issue by kyork-cl** [zettajs/zetta#286]
If you send a QL request to the root resource but don't specify the "server" parameter, a 200 response is returned with zero entities.  I would think this should return a 400 bad request or maybe for convenience it could assume that the "server" value was "*" if not provided.

**Comment by wooliet** [comment]
+1 for defaulting to "*"

**Comment by mdobson** [comment]
Hey @kyork-cl, Thanks for filing this. 

We're going to have this API remain as is. Using the "*" parameter can actually be a very expensive piece of functionality depending on the number of hubs connected to a system. So making it's use as intentional as possible is important for us. 

Returning a 400 doesn't make a whole lot of sense in this case either. It was a valid request issued to the API, but didn't find any results. It's not a bad request. It's just a request without data.

Let me know if you have any questions.

-Matt

**Comment by wooliet** [comment]
If you do not provide a `server` parameter, will the query _ever_ return something other than an empty set?

**Comment by mdobson** [comment]
Yes. Two cases come to mind.

   1. Having a device directly connected to a zetta server in the cloud.
   This could return devices based on a query.
   2. Querying a hub API directly can also return a set of devices.
   Remember the APIs exposed in the cloud are also APIs exposed on the hub.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by wooliet** [comment]
Ahh..I see. Thanks.

**Comment by mdobson** [comment]
No problem. Seems like we have a resolution here. Going to close. Feel free to re-open if there is anything else to address.

**Comment by kyork-cl** [comment]
I feel the current implementation is unintuitive.  The Siren data you get back when you query the root is 

        "actions": [
        {
            "fields": [
                {
                    "name": "server",
                    "type": "text"
                },
                {
                    "name": "ql",
                    "type": "text"
                }
            ],
            "href": "http://localhost:1338/",
            "method": "GET",
            "name": "query-devices",
            "type": "application/x-www-form-urlencoded"
        }
        ],

Which implies that "server" is required.  The current implementation basically defaults the `server` value to "the locally running zetta server".  It is basically a silent redirect to `/servers/{id}?ql=...`, which the user might not be expecting.

I'm ok with `*` not being the default, but I think an error should be returned if `server` is not provided at the root level.

**Comment by mdobson** [comment]
Siren doesn't have a concept of field validations. Sending a request with parameters `server=&ql=where%20type%20%3D%20%27led%27` is perfectly valid. We've decided to keep it as is.

-Matt
