### ISSUE TITLE
Hooks for websocket/peer connections.

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#314]
After digging into zetta and trying find a good/decent way to plug into the websocket requests I realized there really isn't one.

My end goal is to validate a peer request based on a query parameter added to the peering request.

With normal http requests to zetta we can plug into argo's request flow but does not work for `upgrade` requests. We handle the upgrade requests here: https://github.com/zettajs/zetta/blob/master/lib/http_server.js#L83-L87

The only way I was able to get it to work with zetta as is is by copying all event listeners on that `upgrade` event and wrap it in my own method to pre check the request.

Something like: Which of course is not ideal.

```js
.use(function(server) {
  var originalListeners = server.httpServer.server.listeners('upgrade');
  server.httpServer.server.removeAllListeners('upgrade');
  originalListeners.forEach(function(listener) {
    server.httpServer.server.on('upgrade', function(request, socket) {
      console.log('on upgrade', request.url)
      listener(request, socket);
    });
  });
})
```

My proposal would be to add two methods the httpServer or possibly the runtime. That would like:

```js
.use(function() {
  // Peer connection
  server.httpServer.onPeerConnect(function(request, socket, next) {
    // Handle auth logic, 
    next(); // Continue the peering process
  })

  // Regular data websocket connections
  server.httpServer.onWebsocketConnect(function(request, socket, next) {
    // Handle auth logic, 
    next(); // Continue the event_socket process
  })
})
```

@kevinswiber @mdobson Any thoughts?

**Comment by mdobson** [comment]
+1 to the proposal. Seems to be consistent with other hooks we have.
