### ISSUE TITLE
zetta-hue-driver issues

### ISSUE THREAD

**Issue by anandmahato29** [zettajs/zetta#325]
zetta-hue-driver is not working at all with hue emulaor

**Comment by AdamMagaluk** [comment]
Can we move the issue to https://github.com/zettajs/zetta-hue-driver, Thanks.

Is this the hue emulator? http://steveyo.github.io/Hue-Emulator/ We've never tested against or planned on supporting it. Though we would happily accept a pull request.

**Comment by anandmahato29** [comment]
Sorry for late reply, yes it is http://steveyo.github.io/Hue-Emulator/ emulator that i am using. Is there any way to get it working
