### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by kyork-cl** [zettajs/zetta#335]
I'm investigating the source of a system crash in our product and I think I have narrowed it down to the "argo-resource" dependency.  If you install a `resource:request:before` handler, the memory consumption of the program continues to grow until it uses all system memory and crashes.  If you install a `request` instead, the memory leak does not occur.

        var zetta = require('zetta');
        
        zetta()
          // .use(handleWithLeak)
          .use(handleWithoutLeak)
          .listen(1337, function zettaReady() {
            console.log('Running...');
          });
        
        function handleWithLeak(server) {
          server.httpServer.cloud.use(function setupResourceHandler(handle) {
            handle('resource:request:before', function resourceHandler(env, next) {
              next(env);
            });
          });
        }
        
        function handleWithoutLeak(server) {
          server.httpServer.cloud.use(function setupRequestHandler(handle) {
            handle('request', function requestHandler(env, next) {
              next(env);
            });
          });
        }

I'll continue to dig into the "argo-resource" dependency and see if I can locate the source of the leak.

**Comment by kyork-cl** [comment]
The leak is fairly slow, so I'm using Vegeta to expedite the process.   `echo "GET http://127.0.0.1:1337/" | vegeta attack | vegeta report`

**Comment by wooliet** [comment]
@AdamMagaluk _argo-resource/resources.js_ method `_setupRequest` checks for two special pipelines, "resource:request:before" and "resource:request:after". In both cases, if found, the `siphon` method of the pipeline is called.

```javascript
var pre = context.env.pipeline('resource:request:before');
if (pre) {
  pre.siphon(context.env, function(env) {
```

This goes into _pipeworks/pipeworks.js_ method `siphon`, which in turn calls `fit`. 

If I update `fit` with a check to see if the pipeline is already built, the memory issues go away.

```javascript
Pipeworks.prototype.fit = function(options, pipe) {
  if(this.state === 'built') {
    return this;
  }
}
```

This is just a guess on my part as far as the logic goes. The build process creates `LinkedList.Node` instances, which look to be a big contributor to the memory problem. I imagined that once a pipeline has been through its build process, it does not need to go through it again.

**Comment by mdobson** [comment]
Interesting. Rebuilding that pipe every time would definitely make the memory expand.

**Comment by wooliet** [comment]
Would it be possible for _argo/builder.js_ to be updated with the "resource:" pipes? And the `build` method handles the `siphon` creation and such?

**Comment by mdobson** [comment]
Possibly. I don't have cycles to do it though.

**Comment by wooliet** [comment]
Good news. This is not an issue with latest version of pipeworks (1.3.1), and has actually been fixed since 1.3.0 (released March 2015).
 
Here is the commit:
https://github.com/kevinswiber/pipeworks/commit/3f7d02ec0f7d702113605abe32d35e142e57de42

@mdobson or @AdamMagaluk : can you bump the version in all relevant zetta package files?

**Comment by wooliet** [comment]
Das Pulls:

- [ ] https://github.com/argo/argo/pull/59
- [ ] https://github.com/argo/argo-resource/pull/2

**Comment by AdamMagaluk** [comment]
Sorry for the delay, ill get this updated and a zetta release done by end of weekend. Thanks for the debugging effort.

**Comment by AdamMagaluk** [comment]
@wooliet Is it safe to close this now?

**Comment by wooliet** [comment]
I'll leave that to @kyork-cl, since he opened the issue.

**Comment by kyork-cl** [comment]
Yes, the issue looks to be resolved now.  Thanks.
