### ISSUE TITLE
Monitor array of objects

### ISSUE THREAD

**Issue by sadrzadehsina** [zettajs/zetta#356]
Hi,

I am wondering is there any way to monitor an array of objects. I did it like below, but when `consumers` updates with the `add-consumer` endpoint, it does not notify me on the client.

```javascript
function MyDevice() {
  this.consumers = [];
  ...
}

MyDevice.prototype.init = function(config) {
  config
    .monitor('consumers');
  
  config
    .map('add-consumer', this.addConsumer, [{ name: 'consumer', type: 'object' }]);
}

MyDevice.prototype.addConsumer = function( consumer, callback ) {
  this.consumers.push(consumer);
}
```

**Comment by AdamMagaluk** [comment]
See issue in https://github.com/zettajs/zetta-device/issues/24

Also see: https://github.com/zettajs/zetta/wiki/Device#configstreamname-func-options
