### ISSUE TITLE
Logging in the server file

### ISSUE THREAD

**Issue by mdobson** [zettajs/zetta#91]
Any thoughts on opening up logging in the server file as well? We have it every where else basically.

```javascript
var zetta = require('zetta');
var LED = require('./');
var server = zetta()
  .use(LED)
  .listen(1337, function(err) {
    server.log('Error:', err);
  });
```

or

```javascript
var zetta = require('zetta');
var LED = require('./');
zetta()
  .use(LED)
  .listen(1337, function(err) {
    this.log('Error:', err);
  });
```

**Comment by anhldbk** [comment]
This issue should be closed, right? We've already had it: https://github.com/zettajs/zetta/wiki/Logging

**Comment by mdobson** [comment]
Sure do. Thanks for bringing this stale issue to our attention! 

-Matt
